### ISSUE TITLE
Roadmap, To-dos

### ISSUE THREAD

**Issue by timonmasberg** [merged-js/solid-apollo#7] opened 2022-05-26 12:46 UTC
Hi,
in the readme you stated, that this lib is currently under heavy development. What needs to be done? Where can I help? What are known issues? 
Maybe create a GitHub Project for this or add a to-do list to the readme, so I know where to start.

Thanks in advance!

**Comment by Torsten85** [comment] 2022-08-08 08:20
Hello... I've made the README less frightening 😉 

The package works as intended and I don't see any open todos or known issues (it's not an alpha or beta).
But if you encounter anything, it would be great if you could create another issue. For now I'm closing this one.

**Closed by Torsten85** 2022-08-08 08:20 UTC
